version: '3'

services:
  postgres:
    env_file:
      - .env
    image: genkit-smarthome:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000